[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "24"   # sau versiunea ta Node
  NETLIFY_USE_CACHE = "false"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
